language: python
python:
  - 3.5
install:
install:
  - pip install .
  - pip install -r requirements.txt -r test-requirements.txt
script:
  - coverage run --source=tsmppt60_driver setup.py test
after_success:
  - coveralls
