language: python
python:
  - "3.5-dev" # 3.5 development branch
# command to install dependencies
install: "pip install -r requirements.txt -r test-requirements.txt"
# command to run tests
script:
  - coverage run --source=tsmppt60_driver setup.py test
after_success:
  - coveralls